version: "3.9"

services:
  recsys:
    build: .
    image: recsys_app_img
    container_name: recsys_app
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./bd:/bd

    healthcheck:
      test: curl --fail http://localhost:5000/healthcheck || exit 1
      interval: 1h
      timeout: 20s
      retries: 2
      start_period: 3m

    restart: always
